branches:
  only:
    # Tagged releases
    - /^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$/
    # Master
    - master
    # Release branches
    - /^release\/.+$/
    # Develop
    - develop

language: node_js

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - echo "No tests ran"

before_deploy:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp/awscli-bundle.zip"
  - unzip /tmp/awscli-bundle.zip -d /tmp
  - /tmp/awscli-bundle/install -b $HOME/bin/aws
  - export PATH=$PATH:$HOME/bin

deploy:
  # Tagged releases
  - provider: script
    script: ENVIRONMENT=production AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PRODUCTION bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$
  # Release branches
  - provider: script
    script: ENVIRONMENT=release AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_RELEASE AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_RELEASE AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_RELEASE bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.+$
  # Develop
  - provider: script
    script: ENVIRONMENT=staging AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STAGING AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STAGING AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_STAGING bash .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
